language: r
r:
  - oldrel
  - release
  - devel

dist: xenial
services:
  - xvfb
r_check_args: --as-cran --install-args=--build

before_install:
  - sudo apt-get install -y mesa-common-dev libglu1-mesa-dev libmagick++-dev

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov(type = "all")'
